spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/board?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=true
    username: root
    password: 1
  mvc:
    view:
      prefix: /WEB-INF/jsp/
      suffix: .jsp
  resources:
    static-locations: classpath:/static/

mybatis:
  mapper-locations: classpath:/mapper/**/*.xml